name: build
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install paddle2onnx
        run: |
          python -m pip install paddlepaddle -i https://www.paddlepaddle.org.cn/packages/stable/cpu/
          python -m pip install paddleocr
          python -m pip install paddle2onnx
      - name: Convert to ONNX
        run: |
          mkdir original_models
          mkdir onnx_models
          mkdir openvino_models
          mkdir artifacts
          chmod +x ./convert_models.sh && chmod +x ./convert_model.sh
          
          # Run script
          ./convert_models.sh
      - uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: /home/runner/artifacts/*.tar
          tag_name: ${{ github.run_id }}
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}