name: build
on:
  push:
    branches:
        - main
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install paddle2onnx
        run: |
          python -m pip install paddlepaddle -i https://www.paddlepaddle.org.cn/packages/stable/cpu/
          python -m pip install paddleocr
          python -m pip install paddle2onnx
      - name: Convert to ONNX
        run: |
          mkdir original_models
          mkdir converted_models
          
          # Download model
          uvx hf download PaddlePaddle/latin_PP-OCRv5_mobile_rec \
            --local-dir original_models/PaddlePaddle/latin_PP-OCRv5_mobile_rec

          paddle2onnx \
            --model_dir original_models/PaddlePaddle/latin_PP-OCRv5_mobile_rec \
            --model_filename inference.json \
            --params_filename inference.pdiparams \
            --save_file converted_models/latin_PP-OCRv5_mobile_rec.onnx
