name: build
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-1
          restore-keys: |
            ${{ runner.os }}-
      - name: Install paddle2onnx
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv 
          .venv/bin/python -m pip install paddlepaddle -i https://www.paddlepaddle.org.cn/packages/stable/cpu/
          .venv/bin/python -m pip install paddleocr
          .venv/bin/python -m pip install paddle2onnx
      - name: Convert to ONNX
        run: |
          mkdir original_models
          mkdir onnx_models
          mkdir openvino_models
          mkdir artifacts
          chmod +x ./convert_models.sh && chmod +x ./convert_model.sh
          
          # Run script
          ./convert_models.sh
      - uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: /home/runner/work/paddleOCRToOpenVINO/paddleOCRToOpenVINO/artifacts/*.tar
          tag_name: ${{ github.run_id }}
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}